# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 03:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template_management', '0003_merge_20160821_0823'),
        ('subscriber_management', '0003_auto_20160821_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_suject', models.CharField(max_length=150)),
                ('email_from_name', models.CharField(max_length=100)),
                ('email_from_email', models.CharField(max_length=100)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('email_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber_management.List')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_management.Template')),
            ],
        ),
    ]
