# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='email_suject',
            new_name='email_subject',
        ),
    ]
