# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='text_template',
            field=models.TextField(blank=True),
        ),
    ]
