# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import subscriber_management.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=125)),
                ('title', models.CharField(blank=True, max_length=125)),
                ('from_email', models.CharField(blank=True, max_length=125)),
                ('from_email_verified', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=4000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscribe_list/images/')),
                ('token', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=50)),
                ('subscribe_template', models.TextField(blank=True)),
                ('success_template', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('token_subscribe', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=50)),
                ('token_unsubscribe', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=50)),
                ('validated', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('accept_language', models.TextField(blank=True, null=True)),
                ('ip_subscribe', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_validate', models.GenericIPAddressField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber_management.List')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set([('list', 'email')]),
        ),
    ]
