# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=125)),
                ('title', models.CharField(blank=True, max_length=125)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=4000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscribe_list/images/')),
                ('subscribe_template', models.TextField(blank=True)),
                ('success_template', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('accept_language', models.TextField(blank=True)),
                ('timezone', models.IntegerField(blank=True, null=True)),
                ('timezone_str', models.CharField(blank=True, max_length=50)),
                ('member_rating', models.FloatField(blank=True, null=True)),
                ('optin_time', models.DateTimeField(blank=True, null=True)),
                ('optin_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('confim_time', models.DateTimeField(blank=True, null=True)),
                ('confim_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cc', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber_management.List')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set([('list', 'email')]),
        ),
    ]
