# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set([('list', 'email')]),
        ),
    ]
