# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber_management', '0002_auto_20160821_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subscribe_list/images/'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='accept_language',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='timezone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
